packages:
  - 'client'
  - 'server'
allowBuilds:
  esbuild: set this to true or false
  msw: set this to true or false
  serverless: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
onlyBuiltDependencies:
  - msw
resolutions:
  sharp: "^0.33.5"
  sharp-ico: "^0.1.5"
