# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: coatchmactch
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: coatchmatchapp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api-cadastro

stages:
  default:
    params:


plugins:
  - serverless-dynamodb
  - serverless-offline
  

provider:
  timeout: 30
  name: aws
  region: us-east-1
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
          
functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:  # era "resource" (sem o 's')
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: coaches
        AttributeDefinitions:
          - AttributeName: coachId
            AttributeType: S
        KeySchema:
          - AttributeName: coachId  
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    stages:
      - dev
      - default
    start:
      port: 8000
      inMemory: true
      migrate: true  # cria as tabelas automaticamente