# Ambiente local
local:
  stage: local
  region: us-east-1
  endpoint: http://localhost:8000
  accessKeyId: fakeMyKeyId
  secretAccessKey: fakeSecretAccessKey

# Ambiente dev
dev:
  stage: dev
  region: sa-east-1
  apiGatewayId: qht6965nv9 