# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: coachmatch
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: coachmatchapp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: coachmatch



stages:
  dev:
    params:
      stage: ${self:custom.config.stage}
      region: ${self:custom.config.region}
  local:
    params:
      stage: ${self:custom.config.stage}
      region: ${self:custom.config.region}
      endpoint: ${self:custom.config.endpoint}
      access_key_id: ${self:custom.config.accessKeyId}
      secret_access: ${self:custom.config.secretAccessKey}

plugins:
  - serverless-dynamodb
  - serverless-offline
  

provider:
  profile: JoaoAdm
  timeout: 30
  name: aws
  
  httpApi:
    authorizers:
      cognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.sa-east-1.amazonaws.com/sa-east-1_2DDuPPtc0
        audience:
          - 76hul7797npfkmpoju0mbghti7

  stage: ${self:custom.config.stage}
  region: ${self:custom.config.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
          Resource:
            - arn:aws:dynamodb:sa-east-1:138413505977:table/coaches
            - arn:aws:dynamodb:sa-east-1:138413505977:table/student
            - arn:aws:dynamodb:sa-east-1:138413505977:table/gyms

functions:

  gymList:
    handler: src/gyms/list-gyms/handler.handler
    environment:
      STAGE: ${param:stage}
      REGION: ${param:region}
      ENDPOINT: ${param:endpoint, ""}
      ACCESS_KEY_ID: ${param:access_key_id, ""}
      SECRET_ACCESS_KEY: ${param:secret_access, ""}
    events:
      - httpApi:
          path: /gyms
          method: GET
          authorizer:
            name: cognitoAuthorizer

  gymSuggest:
    handler: src/gyms/suggest-gym/handler.handler
    environment:
      STAGE: ${param:stage}
      REGION: ${param:region}
      ENDPOINT: ${param:endpoint, ""}
      ACCESS_KEY_ID: ${param:access_key_id, ""}
      SECRET_ACCESS_KEY: ${param:secret_access, ""}
    events:
      - httpApi:
          path: /gyms/suggest
          method: POST
          authorizer:
            name: cognitoAuthorizer

  coachGetMe:
    handler: src/coaches/get-coach/handler.handler
    environment:
      STAGE: ${param:stage}
      REGION: ${param:region}
      ENDPOINT: ${param:endpoint, ""}
      ACCESS_KEY_ID: ${param:access_key_id, ""}
      SECRET_ACCESS_KEY: ${param:secret_access, ""}
    events:
      - httpApi:
          path: /coaches/me
          method: GET
          authorizer:
            name: cognitoAuthorizer

  coachUpdateMe:
    handler: src/coaches/update-coach/handler.handler
    environment:
      STAGE: ${param:stage}
      REGION: ${param:region}
      ENDPOINT: ${param:endpoint, ""}
      ACCESS_KEY_ID: ${param:access_key_id, ""}
      SECRET_ACCESS_KEY: ${param:secret_access, ""}
    events:
      - httpApi:
          path: /coaches/me
          method: PUT
          authorizer:
            name: cognitoAuthorizer

  coachCreate:
    handler: src/coaches/create-coach/handler.handler
    environment:
      STAGE: ${param:stage}
      REGION: ${param:region}
      ENDPOINT: ${param:endpoint, ""}
      ACCESS_KEY_ID: ${param:access_key_id, ""}
      SECRET_ACCESS_KEY: ${param:secret_access, ""}
    events:
      - cognitoUserPool:
          pool: CoachAccess
          trigger: PostConfirmation
          existing: true

  coachSubmitForReview:
    handler: src/coaches/submit-coach-for-review/handler.handler
    environment:
      STAGE: ${param:stage}
      REGION: ${param:region}
      ENDPOINT: ${param:endpoint, ""}
      ACCESS_KEY_ID: ${param:access_key_id, ""}
      SECRET_ACCESS_KEY: ${param:secret_access, ""}
    events:
      - httpApi:
          path: /coaches/me/submit-for-review
          method: POST
          authorizer:
            name: cognitoAuthorizer
  
  studentCreate:
    handler: src/students/create-student/handler.handler
    environment:
      STAGE: ${param:stage}
      REGION: ${param:region}
      ENDPOINT: ${param:endpoint, ""}
      ACCESS_KEY_ID: ${param:access_key_id, ""}
      SECRET_ACCESS_KEY: ${param:secret_access, ""}
    events:
      - cognitoUserPool:
          pool: StudentAccess
          trigger: PostConfirmation
          existing: true

  studentGetProfile:
    handler: src/students/get-student/handler.handler
    environment:
      STAGE: ${param:stage}
      REGION: ${param:region}
      ENDPOINT: ${param:endpoint, ""}
      ACCESS_KEY_ID: ${param:access_key_id, ""}
      SECRET_ACCESS_KEY: ${param:secret_access, ""}
    events:
      - httpApi:
          path: /clients/me
          method: GET
          authorizer:
            name: cognitoAuthorizer

  studentUpdateProfile:
    handler: src/students/update-student-profile/handler.handler
    environment:
      STAGE: ${param:stage}
      REGION: ${param:region}
      ENDPOINT: ${param:endpoint, ""}
      ACCESS_KEY_ID: ${param:access_key_id, ""}
      SECRET_ACCESS_KEY: ${param:secret_access, ""}
    events:
      - httpApi:
          path: /clients/me/profile
          method: POST
          authorizer:
            name: cognitoAuthorizer

  studentUpdateHealth:
    handler: src/students/update-student-health/handler.handler
    environment:
      STAGE: ${param:stage}
      REGION: ${param:region}
      ENDPOINT: ${param:endpoint, ""}
      ACCESS_KEY_ID: ${param:access_key_id, ""}
      SECRET_ACCESS_KEY: ${param:secret_access, ""}
    events:
      - httpApi:
          path: /clients/me/health
          method: POST
          authorizer:
            name: cognitoAuthorizer
        

resources: 
  Conditions:
    IsLocal: !Equals [ "${param:stage}", "local"]  
  Resources:
    gymsTable:
      Type: AWS::DynamoDB::Table
      Condition: IsLocal
      Properties:
        TableName: gyms
        AttributeDefinitions:
          - AttributeName: gymId
            AttributeType: S
        KeySchema:
          - AttributeName: gymId  
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    usersTable:
      Type: AWS::DynamoDB::Table
      Condition: IsLocal
      Properties:
        TableName: coaches
        AttributeDefinitions:
          - AttributeName: coachId
            AttributeType: S
        KeySchema:
          - AttributeName: coachId  
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    studentTable:
      Type: AWS::DynamoDB::Table
      Condition: IsLocal
      Properties:
        TableName: student
        AttributeDefinitions:
          - AttributeName: studentId
            AttributeType: S
        KeySchema:
          - AttributeName: studentId  
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1



custom:
  config: ${file(./config.yml)}
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true  # cria as tabelas automaticamente
  serverless-offline:
    ignoreJWTSignature: true